# Generated by Django 2.0 on 2017-12-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='cellphone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='counrty',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
