# Generated by Django 2.0 on 2017-12-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20171229_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='in_association',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='is_buy_clothes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='is_buy_coat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='school_id',
            field=models.CharField(default=104321031, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='school_voip',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
