# Generated by Django 2.0 on 2017-12-30 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_auto_20171229_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='github',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
