# Generated by Django 2.0 on 2017-12-30 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_remove_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
