# Generated by Django 2.0 on 2018-01-12 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0011_member_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb', models.URLField(max_length=100)),
                ('category', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='loginInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_IP', models.GenericIPAddressField(blank=True, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_buy_coat', models.BooleanField(default=False)),
                ('is_buy_clothes', models.BooleanField(default=False)),
                ('enroll_date', models.DateTimeField(blank=True, null=True)),
                ('leave_date', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='cellphone',
        ),
        migrations.RemoveField(
            model_name='member',
            name='counrty',
        ),
        migrations.RemoveField(
            model_name='member',
            name='fb',
        ),
        migrations.RemoveField(
            model_name='member',
            name='github',
        ),
        migrations.RemoveField(
            model_name='member',
            name='in_association',
        ),
        migrations.RemoveField(
            model_name='member',
            name='is_buy_clothes',
        ),
        migrations.RemoveField(
            model_name='member',
            name='is_buy_coat',
        ),
        migrations.RemoveField(
            model_name='member',
            name='last_IP',
        ),
        migrations.RemoveField(
            model_name='member',
            name='personal_web',
        ),
        migrations.RemoveField(
            model_name='member',
            name='school_voip',
        ),
        migrations.AddField(
            model_name='sam',
            name='member',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Member'),
        ),
        migrations.AddField(
            model_name='contact',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member'),
        ),
    ]
